# List of interests
interests = [
    "Artificial Intelligence",
    "Internet of Things (IoT)",
    "Blockchain",
    "Augmented Reality (AR) / Virtual Reality (VR)",
    "Women in Tech Initiatives",
    "Diversity and Inclusion in STEM",
    "Mentorship Programs",
    "Networking Events",
    "Leadership Development",
    "Public Speaking",
    "Technical Writing",
    "Personal Branding",
    "STEM Education for Girls",
    "Gender Equality in Tech",
    "Advocacy for Underrepresented Groups",
    "Photography",
    "Traveling",
    "Blogging/Vlogging",
    "Volunteering",
    "Mental Health Awareness",
    "Work-Life Balance",
    "Physical Fitness",
    "Design (Graphic, Web, Fashion)",
    "Music and Arts",
    "Creative Writing",
]
