# List of skills
skills = [
    "Python",
    "Java",
    "JavaScript",
    "C++",
    "Ruby",
    "Go",
    "Swift",
    "Kotlin",
    "HTML/CSS",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "PHP",
    "Data Analysis",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing (NLP)",
    "Data Visualization",
    "SQL",
    "TensorFlow",
    "PyTorch",
    "AWS (Amazon Web Services)",
    "Azure",
    "Google Cloud Platform (GCP)",
    "Docker",
    "Kubernetes",
    "Ethical Hacking",
    "Network Security",
    "Information Security",
    "Risk Assessment",
    "Compliance and Regulations",
    "CI/CD (Continuous Integration/Continuous Deployment)",
    "Automation Tools (e.g., Jenkins, Git)",
    "Monitoring and Logging",
    "User Research",
    "Prototyping",
    "Wireframing",
    "User Interface Design",
    "Usability Testing",
    "Agile Methodologies",
    "Scrum",
    "Kanban",
    "Jira",
    "Trello",
]
